name: 'build package'

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    paths-ignore:
    - '.github/workflows/**'
    - '.github/.Dockerfile.tmpl'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        id: tag
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      - name: Short tag
        id: short
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          short-tag=$(echo ${{ steps.tag.outputs.tag }} | cut -f1-2 -d'.')
          echo ::set-output name=short-tag::$short-tag

      - id: debug1
        shell: bash
        run: |
          echo ${{ steps.tag.outputs.tag }}
      - id: debug2
        shell: bash
        run: |
          echo ${{ steps.short.outputs.tag }}
      - id: debug3
        shell: bash
        run: |
          echo ${{ steps.tag.outputs.tag }}
          echo ${{ steps.short.outputs.tag }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:${{ steps.short.outputs.tag }}
